test:
	go test -v ./...

test_redis:
	GO_MESSAGE_QUEUE_CONFIG="testdata/config/redis.yaml" go test -v ./...

test_mysql:
	GO_MESSAGE_QUEUE_CONFIG="testdata/config/mysql.yaml" go test -v ./...

test_debug:
	GO_ROUTER_ENABLE_LOGGING=1 GO_MESSAGE_QUEUE_DEBUG=1 go test -v ./...
